import { createHash, randomUUID } from 'node:crypto';
import type { RequestContext, TrustPersistence } from '@assurapay/shared';
import { requireActiveWorkspace } from '@assurapay/shared';
export type LegalPolicy = { id: string; workspaceId?: string; policyKey: string; name: string; policyType: string; jurisdictionCode?: string; language: string; status: 'DRAFT' | 'ACTIVE' | 'ARCHIVED'; createdAt: string; updatedAt: string };
export type LegalPolicyVersion = { id: string; legalPolicyId: string; version: number; contentReference: string; contentHash: string; effectiveFrom: string; effectiveTo?: string; publicationStatus: 'DRAFT' | 'PUBLISHED' | 'SUPERSEDED'; publishedBy?: string; publishedAt?: string; supersedesVersionId?: string; createdAt: string };
export type PolicyAssignment = { id: string; workspaceId: string; legalPolicyVersionId: string; targetType: string; targetId: string; mandatory: boolean; acceptanceRequired: boolean; effectiveFrom: string; effectiveTo?: string; status: 'ACTIVE' | 'INACTIVE'; createdAt: string; updatedAt: string };
export type PolicyAcceptance = { id: string; workspaceId: string; legalPolicyVersionId: string; principalType: string; principalId: string; acceptanceMethod: string; acceptedAt: string; sourceContext: string; evidenceReference: string; withdrawnAt?: string; withdrawalReason?: string; createdAt: string };
export type ConsentRecord = { id: string; workspaceId: string; principalId: string; consentType: string; policyVersionId: string; status: 'GRANTED' | 'WITHDRAWN' | 'EXPIRED' | 'REVOKED' | 'NOT_REQUIRED'; grantedAt: string; withdrawnAt?: string; reason?: string; createdAt: string };
export type LegalHold = { id: string; workspaceId: string; objectType: string; objectId: string; reason: string; status: 'ACTIVE' | 'RELEASED' | 'EXPIRED' | 'SUPERSEDED'; placedBy: string; placedAt: string; releasedBy?: string; releasedAt?: string; releaseReason?: string; createdAt: string; updatedAt: string; version: number };
export type SignaturePolicy = { id: string; workspaceId: string; jurisdictionCode: string; contractType: string; transactionType: string; assuranceLevel: string; witnessRequired: boolean; status: 'ACTIVE' | 'INACTIVE'; priority: number; createdAt: string; version: number };
export class LegalService {
  constructor(private readonly store: TrustPersistence) {}
  async createPolicy(context: RequestContext, input: { policyKey: string; name: string; policyType: string; jurisdictionCode?: string; language?: string; global?: boolean }) { if (!input.global) requireActiveWorkspace(context); const now = new Date().toISOString(); const policy: LegalPolicy = { id: randomUUID(), workspaceId: input.global ? undefined : context.activeWorkspaceId, policyKey: input.policyKey, name: input.name, policyType: input.policyType, jurisdictionCode: input.jurisdictionCode, language: input.language ?? 'en', status: 'DRAFT', createdAt: now, updatedAt: now }; await this.store.append('legalPolicies', policy); return policy; }
  async createVersion(context: RequestContext, policyId: string, input: { contentReference: string; content: string; effectiveFrom: string }) { const policy = await this.requirePolicy(policyId, context); const versions = (await this.store.list<LegalPolicyVersion>('legalPolicyVersions')).filter((entry) => entry.legalPolicyId === policy.id); const previous = versions.sort((a, b) => b.version - a.version)[0]; const version: LegalPolicyVersion = { id: randomUUID(), legalPolicyId: policy.id, version: (previous?.version ?? 0) + 1, contentReference: input.contentReference, contentHash: createHash('sha256').update(input.content).digest('hex'), effectiveFrom: input.effectiveFrom, publicationStatus: 'DRAFT', supersedesVersionId: previous?.id, createdAt: new Date().toISOString() }; await this.store.append('legalPolicyVersions', version); return version; }
  async publishVersion(context: RequestContext, id: string) { requireActiveWorkspace(context); const version = (await this.store.list<LegalPolicyVersion>('legalPolicyVersions')).find((entry) => entry.id === id); if (!version) throw new Error('POLICY_VERSION_NOT_FOUND'); await this.requirePolicy(version.legalPolicyId, context); if (version.publicationStatus !== 'DRAFT') throw new Error('PUBLISHED_POLICY_IMMUTABLE'); for (const current of (await this.store.list<LegalPolicyVersion>('legalPolicyVersions')).filter((entry) => entry.legalPolicyId === version.legalPolicyId && entry.publicationStatus === 'PUBLISHED')) await this.store.replace('legalPolicyVersions', { ...current, publicationStatus: 'SUPERSEDED', effectiveTo: version.effectiveFrom }); const published = { ...version, publicationStatus: 'PUBLISHED' as const, publishedBy: context.actorUserId, publishedAt: new Date().toISOString() }; await this.store.replace('legalPolicyVersions', published); await this.store.audit({ tenantId: context.tenantId, workspaceId: context.activeWorkspaceId, actorId: context.actorUserId, eventType: 'LegalPolicyPublished', aggregateType: 'LegalPolicyVersion', aggregateId: id, correlationId: context.correlationId, metadata: { version: version.version } }); return published; }
  async assignPolicy(context: RequestContext, input: Omit<PolicyAssignment, 'id' | 'workspaceId' | 'createdAt' | 'updatedAt'>) { requireActiveWorkspace(context); const version = await this.requirePublished(input.legalPolicyVersionId); const policy = await this.requirePolicy(version.legalPolicyId, context); if (policy.workspaceId && policy.workspaceId !== context.activeWorkspaceId) throw new Error('POLICY_SCOPE_DENIED'); const now = new Date().toISOString(); const assignment: PolicyAssignment = { id: randomUUID(), workspaceId: context.activeWorkspaceId, ...input, createdAt: now, updatedAt: now }; await this.store.append('policyAssignments', assignment); return assignment; }
  async acceptPolicy(context: RequestContext, versionId: string, input: { principalType: string; principalId: string; acceptanceMethod: string; sourceContext: string; evidenceReference: string }) { requireActiveWorkspace(context); const version = await this.requirePublished(versionId); const policy = await this.requirePolicy(version.legalPolicyId, context); if (policy.workspaceId && policy.workspaceId !== context.activeWorkspaceId) throw new Error('POLICY_SCOPE_DENIED'); const acceptance: PolicyAcceptance = { id: randomUUID(), workspaceId: context.activeWorkspaceId, legalPolicyVersionId: version.id, ...input, acceptedAt: new Date().toISOString(), createdAt: new Date().toISOString() }; await this.store.append('policyAcceptances', acceptance); await this.store.audit({ tenantId: context.tenantId, workspaceId: context.activeWorkspaceId, actorId: context.actorUserId, eventType: 'PolicyAccepted', aggregateType: 'PolicyAcceptance', aggregateId: acceptance.id, correlationId: context.correlationId, metadata: { legalPolicyVersionId: version.id, method: input.acceptanceMethod } }); return acceptance; }
  async withdrawAcceptance(context: RequestContext, id: string, reason: string) { requireActiveWorkspace(context); const acceptance = (await this.store.list<PolicyAcceptance>('policyAcceptances')).find((entry) => entry.id === id && entry.workspaceId === context.activeWorkspaceId); if (!acceptance) throw new Error('ACCEPTANCE_NOT_FOUND'); if (acceptance.withdrawnAt) throw new Error('ACCEPTANCE_ALREADY_WITHDRAWN'); const updated = { ...acceptance, withdrawnAt: new Date().toISOString(), withdrawalReason: reason }; await this.store.replace('policyAcceptances', updated); return updated; }
  async grantConsent(context: RequestContext, input: { principalId: string; consentType: string; policyVersionId: string }) { requireActiveWorkspace(context); await this.requirePublished(input.policyVersionId); const consent: ConsentRecord = { id: randomUUID(), workspaceId: context.activeWorkspaceId, ...input, status: 'GRANTED', grantedAt: new Date().toISOString(), createdAt: new Date().toISOString() }; await this.store.append('consents', consent); return consent; }
  async withdrawConsent(context: RequestContext, id: string, reason: string) { requireActiveWorkspace(context); const consent = (await this.store.list<ConsentRecord>('consents')).find((entry) => entry.id === id && entry.workspaceId === context.activeWorkspaceId); if (!consent) throw new Error('CONSENT_NOT_FOUND'); const updated = { ...consent, status: 'WITHDRAWN' as const, withdrawnAt: new Date().toISOString(), reason }; await this.store.replace('consents', updated); return updated; }
  async placeHold(context: RequestContext, input: { objectType: string; objectId: string; reason: string }) { requireActiveWorkspace(context); const now = new Date().toISOString(); const hold: LegalHold = { id: randomUUID(), workspaceId: context.activeWorkspaceId, ...input, status: 'ACTIVE', placedBy: context.actorUserId, placedAt: now, createdAt: now, updatedAt: now, version: 1 }; await this.store.append('legalHolds', hold); await this.store.audit({ tenantId: context.tenantId, workspaceId: context.activeWorkspaceId, actorId: context.actorUserId, eventType: 'LegalHoldPlaced', aggregateType: 'LegalHold', aggregateId: hold.id, correlationId: context.correlationId, metadata: { objectType: input.objectType, objectId: input.objectId } }); return hold; }
  async assertNoLegalHold(context: RequestContext, objectType: string, objectId: string) { requireActiveWorkspace(context); if ((await this.store.list<LegalHold>('legalHolds')).some((entry) => entry.workspaceId === context.activeWorkspaceId && entry.objectType === objectType && entry.objectId === objectId && entry.status === 'ACTIVE')) throw new Error('LEGAL_HOLD_ACTIVE'); }
  async releaseHold(context: RequestContext, id: string, reason: string, authorized: boolean) { requireActiveWorkspace(context); if (!authorized) throw new Error('LEGAL_HOLD_RELEASE_DENIED'); const hold = (await this.store.list<LegalHold>('legalHolds')).find((entry) => entry.id === id && entry.workspaceId === context.activeWorkspaceId && entry.status === 'ACTIVE'); if (!hold) throw new Error('LEGAL_HOLD_NOT_FOUND'); const now = new Date().toISOString(); const updated = { ...hold, status: 'RELEASED' as const, releasedBy: context.actorUserId, releasedAt: now, releaseReason: reason, updatedAt: now, version: hold.version + 1 }; await this.store.replace('legalHolds', updated); return updated; }
  async createSignaturePolicy(context: RequestContext, input: Omit<SignaturePolicy, 'id' | 'workspaceId' | 'createdAt' | 'version'>) { requireActiveWorkspace(context); const policy: SignaturePolicy = { id: randomUUID(), workspaceId: context.activeWorkspaceId, ...input, createdAt: new Date().toISOString(), version: 1 }; await this.store.append('signaturePolicies', policy); return policy; }
  async resolveSignaturePolicy(context: RequestContext, jurisdictionCode: string, contractType: string, transactionType: string) { requireActiveWorkspace(context); return (await this.store.list<SignaturePolicy>('signaturePolicies')).filter((entry) => entry.workspaceId === context.activeWorkspaceId && entry.status === 'ACTIVE' && entry.jurisdictionCode === jurisdictionCode && entry.contractType === contractType && entry.transactionType === transactionType).sort((a, b) => b.priority - a.priority || a.id.localeCompare(b.id))[0] ?? null; }
  private async requirePolicy(id: string, context: RequestContext) { const policy = (await this.store.list<LegalPolicy>('legalPolicies')).find((entry) => entry.id === id && (!entry.workspaceId || entry.workspaceId === context.activeWorkspaceId)); if (!policy) throw new Error('LEGAL_POLICY_NOT_FOUND'); return policy; }
  private async requirePublished(id: string) { const version = (await this.store.list<LegalPolicyVersion>('legalPolicyVersions')).find((entry) => entry.id === id && entry.publicationStatus === 'PUBLISHED'); if (!version) throw new Error('POLICY_VERSION_NOT_PUBLISHED'); return version; }
}
