import { createHash, randomUUID } from 'node:crypto';

export * from './assertions';
export * from './gateway';
export * from './issuance';

import type { AssuranceLevel, RequestContext, TrustPersistence } from '@assurapay/shared';

export type IdentityStatus = 'PENDING_VERIFICATION' | 'ACTIVE' | 'SUSPENDED' | 'LOCKED' | 'DISABLED' | 'DELETED';
export type UserIdentity = { id: string; tenantNeutralSubjectId: string; email: string; phone?: string; displayName: string; legalName?: string; status: IdentityStatus; primaryAuthenticationMethod: string; identityAssuranceLevel: AssuranceLevel; emailVerifiedAt?: string; phoneVerifiedAt?: string; lastAuthenticatedAt?: string; createdAt: string; updatedAt: string; version: number };
export type AuthenticationMethod = { id: string; userId: string; methodType: string; provider: string; providerSubjectReference: string; status: 'PENDING' | 'VERIFIED' | 'REVOKED'; verifiedAt?: string; lastUsedAt?: string; createdAt: string; updatedAt: string };
export type UserSession = { id: string; userId: string; workspaceId?: string; sessionTokenHash: string; authenticationMethodId: string; identityAssuranceLevel: AssuranceLevel; deviceId?: string; ipContext?: string; userAgentContext?: string; issuedAt: string; expiresAt: string; lastSeenAt: string; revokedAt?: string; revokedBy?: string; revocationReason?: string; status: 'ACTIVE' | 'REVOKED' | 'EXPIRED'; createdAt: string };
export type TrustedDevice = { id: string; userId: string; deviceFingerprintHash: string; displayName: string; deviceType: string; trustStatus: 'SEEN' | 'TRUSTED' | 'REVOKED'; firstSeenAt: string; lastSeenAt: string; trustedAt?: string; trustExpiresAt?: string; revokedAt?: string; createdAt: string; updatedAt: string };
export type StepUpChallenge = { id: string; userId: string; sessionId: string; requiredAssuranceLevel: AssuranceLevel; reason: string; challengeType: string; status: 'PENDING' | 'COMPLETED' | 'EXPIRED' | 'FAILED'; issuedAt: string; expiresAt: string; completedAt?: string; createdAt: string };

const hash = (value: string) => createHash('sha256').update(value).digest('hex');
export class IdentityService {
  constructor(private readonly store: TrustPersistence) {}
  async register(input: { email: string; displayName: string; correlationId: string }): Promise<UserIdentity> {
    const email = input.email.trim().toLowerCase(); if (!email.includes('@')) throw new Error('VALID_EMAIL_REQUIRED');
    if ((await this.store.list<UserIdentity>('identities')).some((entry) => entry.email === email && entry.status !== 'DELETED')) throw new Error('IDENTITY_EXISTS');
    const now = new Date().toISOString(); const identity: UserIdentity = { id: randomUUID(), tenantNeutralSubjectId: randomUUID(), email, displayName: input.displayName.trim(), status: 'PENDING_VERIFICATION', primaryAuthenticationMethod: 'PASSWORDLESS_EMAIL', identityAssuranceLevel: 'IAL0_UNVERIFIED', createdAt: now, updatedAt: now, version: 1 };
    await this.store.append('identities', identity); await this.store.audit({ actorId: identity.id, eventType: 'IdentityRegistered', aggregateType: 'UserIdentity', aggregateId: identity.id, correlationId: input.correlationId, metadata: { method: 'PASSWORDLESS_EMAIL' } }); await this.store.emit({ aggregateType: 'UserIdentity', aggregateId: identity.id, eventType: 'IdentityRegistered', eventVersion: 1, payload: { userId: identity.id }, correlationId: input.correlationId }); return identity;
  }
  async activate(userId: string, correlationId: string) { const user = await this.requireIdentity(userId); if (user.status !== 'PENDING_VERIFICATION') throw new Error('INVALID_IDENTITY_STATE'); const now = new Date().toISOString(); const updated = { ...user, status: 'ACTIVE' as const, identityAssuranceLevel: 'IAL1_BASIC' as const, emailVerifiedAt: now, updatedAt: now, version: user.version + 1 }; await this.store.replace('identities', updated); await this.store.audit({ actorId: userId, eventType: 'IdentityActivated', aggregateType: 'UserIdentity', aggregateId: userId, correlationId, metadata: {} }); return updated; }
  async registerAuthenticationMethod(userId: string, input: { methodType: string; provider: string; providerSubjectReference: string }) { await this.requireIdentity(userId); const now = new Date().toISOString(); const method: AuthenticationMethod = { id: randomUUID(), userId, ...input, providerSubjectReference: hash(input.providerSubjectReference), status: 'VERIFIED', verifiedAt: now, createdAt: now, updatedAt: now }; await this.store.append('authenticationMethods', method); return method; }
  async login(input: { email: string; rawSessionToken: string; authenticationMethodId?: string; deviceFingerprint?: string; ipContext?: string; userAgentContext?: string; correlationId: string }) {
    const user = (await this.store.list<UserIdentity>('identities')).find((entry) => entry.email === input.email.trim().toLowerCase()); if (!user || user.status !== 'ACTIVE') { await this.store.audit({ actorId: user?.id ?? 'anonymous', eventType: 'AuthenticationFailed', aggregateType: 'UserIdentity', aggregateId: user?.id ?? 'unknown', correlationId: input.correlationId, metadata: { reason: 'ACCOUNT_UNAVAILABLE' } }); throw new Error('AUTHENTICATION_DENIED'); }
    const method = input.authenticationMethodId ? (await this.store.list<AuthenticationMethod>('authenticationMethods')).find((entry) => entry.id === input.authenticationMethodId && entry.userId === user.id && entry.status === 'VERIFIED') : undefined; const methodId = method?.id ?? (await this.registerAuthenticationMethod(user.id, { methodType: 'PASSWORDLESS_EMAIL', provider: 'deterministic', providerSubjectReference: user.email })).id;
    let deviceId: string | undefined; if (input.deviceFingerprint) deviceId = (await this.registerDevice(user.id, input.deviceFingerprint, 'Current device', 'BROWSER')).id;
    const now = new Date(); const session: UserSession = { id: randomUUID(), userId: user.id, sessionTokenHash: hash(input.rawSessionToken), authenticationMethodId: methodId, identityAssuranceLevel: user.identityAssuranceLevel, deviceId, ipContext: input.ipContext, userAgentContext: input.userAgentContext, issuedAt: now.toISOString(), expiresAt: new Date(now.getTime() + 8 * 60 * 60 * 1000).toISOString(), lastSeenAt: now.toISOString(), status: 'ACTIVE', createdAt: now.toISOString() }; await this.store.append('sessions', session); await this.store.audit({ actorId: user.id, eventType: 'AuthenticationSucceeded', aggregateType: 'UserSession', aggregateId: session.id, correlationId: input.correlationId, metadata: { assurance: session.identityAssuranceLevel } }); await this.store.emit({ aggregateType: 'UserSession', aggregateId: session.id, eventType: 'SessionCreated', eventVersion: 1, payload: { userId: user.id }, correlationId: input.correlationId }); return { session, token: input.rawSessionToken };
  }
  async resolveSession(rawToken: string): Promise<UserSession> { const tokenHash = hash(rawToken); const session = (await this.store.list<UserSession>('sessions')).find((entry) => entry.sessionTokenHash === tokenHash); if (!session || session.status !== 'ACTIVE' || Date.parse(session.expiresAt) <= Date.now()) throw new Error('SESSION_INVALID'); const user = await this.requireIdentity(session.userId); if (user.status !== 'ACTIVE') throw new Error('IDENTITY_INACTIVE'); return session; }
  async revokeSession(id: string, context: RequestContext, reason: string) { const session = (await this.store.list<UserSession>('sessions')).find((entry) => entry.id === id && entry.userId === context.actorUserId); if (!session) throw new Error('SESSION_NOT_FOUND'); const updated = { ...session, status: 'REVOKED' as const, revokedAt: new Date().toISOString(), revokedBy: context.actorUserId, revocationReason: reason }; await this.store.replace('sessions', updated); await this.store.audit({ actorId: context.actorUserId, eventType: 'SessionRevoked', aggregateType: 'UserSession', aggregateId: id, correlationId: context.correlationId, metadata: { reason } }); return updated; }
  /** Revoked sequentially: each revocation writes an audit record, and the ledger's hash chain is only verifiable if links are appended one at a time. */
  async revokeAll(userId: string, context: RequestContext) { const active = (await this.store.list<UserSession>('sessions')).filter((entry) => entry.userId === userId && entry.status === 'ACTIVE'); const revoked: UserSession[] = []; for (const entry of active) revoked.push(await this.revokeSession(entry.id, context, 'LOGOUT_ALL')); return revoked; }
  async registerDevice(userId: string, fingerprint: string, displayName: string, deviceType: string) { await this.requireIdentity(userId); const now = new Date().toISOString(); const fingerprintHash = hash(fingerprint); const existing = (await this.store.list<TrustedDevice>('devices')).find((entry) => entry.userId === userId && entry.deviceFingerprintHash === fingerprintHash); if (existing) { const updated = { ...existing, lastSeenAt: now, updatedAt: now }; await this.store.replace('devices', updated); return updated; } const device: TrustedDevice = { id: randomUUID(), userId, deviceFingerprintHash: fingerprintHash, displayName, deviceType, trustStatus: 'SEEN', firstSeenAt: now, lastSeenAt: now, createdAt: now, updatedAt: now }; await this.store.append('devices', device); return device; }
  async trustDevice(id: string, context: RequestContext) { const device = (await this.store.list<TrustedDevice>('devices')).find((entry) => entry.id === id && entry.userId === context.actorUserId); if (!device) throw new Error('DEVICE_NOT_FOUND'); const now = new Date(); const updated = { ...device, trustStatus: 'TRUSTED' as const, trustedAt: now.toISOString(), trustExpiresAt: new Date(now.getTime() + 30 * 86400000).toISOString(), updatedAt: now.toISOString() }; await this.store.replace('devices', updated); return updated; }
  async requestStepUp(input: { userId: string; sessionId: string; requiredAssuranceLevel: AssuranceLevel; reason: string; challengeType: string; ttlMs?: number }) { const session = (await this.store.list<UserSession>('sessions')).find((entry) => entry.id === input.sessionId && entry.userId === input.userId && entry.status === 'ACTIVE'); if (!session) throw new Error('SESSION_INVALID'); const now = new Date(); const challenge: StepUpChallenge = { id: randomUUID(), ...input, status: 'PENDING', issuedAt: now.toISOString(), expiresAt: new Date(now.getTime() + (input.ttlMs ?? 300000)).toISOString(), createdAt: now.toISOString() }; await this.store.append('stepUpChallenges', challenge); return challenge; }
  async completeStepUp(id: string, userId: string) { const challenge = (await this.store.list<StepUpChallenge>('stepUpChallenges')).find((entry) => entry.id === id && entry.userId === userId); if (!challenge) throw new Error('CHALLENGE_NOT_FOUND'); if (challenge.status !== 'PENDING' || Date.parse(challenge.expiresAt) <= Date.now()) throw new Error('CHALLENGE_EXPIRED'); const updated = { ...challenge, status: 'COMPLETED' as const, completedAt: new Date().toISOString() }; await this.store.replace('stepUpChallenges', updated); return updated; }
  private async requireIdentity(id: string) { const user = (await this.store.list<UserIdentity>('identities')).find((entry) => entry.id === id); if (!user) throw new Error('IDENTITY_NOT_FOUND'); return user; }
}
