import { createHash, randomUUID } from 'node:crypto';
import type { RequestContext, TrustPersistence } from '@assurapay/shared';
import { requireActiveWorkspace } from '@assurapay/shared';
const now=()=>new Date().toISOString(); const ws=(c:RequestContext)=>{requireActiveWorkspace(c);return c.activeWorkspaceId}; const hash=(v:unknown)=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
export type EscrowPaymentMode='DIRECT'|'MILESTONE_ESCROW'|'FULL_ESCROW'|'DEPOSIT_MILESTONES'|'RETAINER'|'PAY_ON_DELIVERY'|'EXTERNAL_PAYMENT';
export type EscrowInstruction={id:string;workspaceId:string;agreementId:string;agreementVersionId:string;milestoneId:string;paymentMode:EscrowPaymentMode;amountMinor:number;currency:string;providerKey?:string;releaseConditions:string[];inspectionWindowHours?:number;instructionHash:string;status:'COMPILED'|'FUNDING_PENDING'|'FUNDED'|'SUPERSEDED';createdAt:string};
export type PaymentReadiness={id:string;workspaceId:string;escrowInstructionId:string;milestoneId:string;score:number;eligible:boolean;blockers:string[];evaluatedAt:string};
type Funding={id:string;workspaceId:string;milestoneId:string;currency:string;committedAmountMinor:number;status:string}; type Eligibility={workspaceId:string;milestoneId:string;eligible:boolean;blockers:string[]}; type Invoice={workspaceId:string;milestoneId:string;currency:string;amountMinor:number;status:string}; type Hold={workspaceId:string;milestoneId?:string;active:boolean}; type Certificate={workspaceId:string;milestoneId:string;status:string};
async function emit(s:TrustPersistence,c:RequestContext,e:string,t:string,id:string,p:Record<string,unknown>){await s.audit({tenantId:c.tenantId,workspaceId:ws(c),actorId:c.actorUserId,eventType:e,aggregateType:t,aggregateId:id,correlationId:c.correlationId,metadata:p});await s.emit({tenantId:c.tenantId,workspaceId:ws(c),aggregateType:t,aggregateId:id,eventType:e,eventVersion:1,payload:p,correlationId:c.correlationId})} const latest=<T>(a:T[])=>a[a.length-1];

export class AgreementEscrowCompiler{constructor(private readonly store:TrustPersistence){} async compile(c:RequestContext,i:{agreementId:string;agreementVersionId:string;milestoneId:string;paymentMode:EscrowPaymentMode;amountMinor:number;currency:string;providerKey?:string;releaseConditions:string[];inspectionWindowHours?:number}){const w=ws(c);
 const versions=await this.store.list<any>('agreementVersions'); const version=versions.find(x=>x.id===i.agreementVersionId&&x.workspaceId===w&&(x.agreementId===undefined||x.agreementId===i.agreementId)); if(!version)throw new Error('AGREEMENT_VERSION_NOT_FOUND');
 const activations=await this.store.list<any>('agreementActivations'); const activation=latest(activations.filter(x=>x.workspaceId===w&&x.agreementId===i.agreementId&&(x.agreementVersionId===i.agreementVersionId||x.executedVersionId===i.agreementVersionId))); const agreements=await this.store.list<any>('agreements'); const agreement=agreements.find(x=>x.id===i.agreementId&&x.workspaceId===w); const executable=(activation&&['EXECUTED','ACTIVE'].includes(activation.status))||(agreement&&['EXECUTED','ACTIVE'].includes(agreement.status)&&(!agreement.executedVersionId||agreement.executedVersionId===i.agreementVersionId)); if(!executable)throw new Error('AGREEMENT_NOT_EXECUTED');
 if(!Number.isInteger(i.amountMinor)||i.amountMinor<=0)throw new Error('AMOUNT_MUST_BE_POSITIVE_INTEGER_MINOR_UNITS');if(!/^[A-Z]{3}$/.test(i.currency))throw new Error('INVALID_CURRENCY');if(!i.releaseConditions.length)throw new Error('RELEASE_CONDITIONS_REQUIRED'); const old=(await this.store.list<EscrowInstruction>('escrowInstructions')).find(x=>x.workspaceId===w&&x.agreementVersionId===i.agreementVersionId&&x.milestoneId===i.milestoneId&&x.status!=='SUPERSEDED');if(old)return old;const immutable={...i,releaseConditions:[...i.releaseConditions].sort()};const x:EscrowInstruction={id:randomUUID(),workspaceId:w,...immutable,instructionHash:hash(immutable),status:['MILESTONE_ESCROW','FULL_ESCROW','DEPOSIT_MILESTONES'].includes(i.paymentMode)?'FUNDING_PENDING':'COMPILED',createdAt:now()};await this.store.append('escrowInstructions',x);await emit(this.store,c,'EscrowInstructionCompiled','EscrowInstruction',x.id,{agreementId:x.agreementId,agreementVersionId:x.agreementVersionId,milestoneId:x.milestoneId,instructionHash:x.instructionHash});return x}}

/** Readiness derives canonical facts; caller supplies identity only. */
export class PaymentReadinessEngine{constructor(private readonly store:TrustPersistence){} async assess(c:RequestContext,i:{escrowInstructionId:string;milestoneId:string}){const w=ws(c),x=(await this.store.list<EscrowInstruction>('escrowInstructions')).find(v=>v.id===i.escrowInstructionId&&v.workspaceId===w);if(!x)throw new Error('ESCROW_INSTRUCTION_NOT_FOUND');if(x.milestoneId!==i.milestoneId)throw new Error('MILESTONE_INSTRUCTION_MISMATCH');const required=['MILESTONE_ESCROW','FULL_ESCROW','DEPOSIT_MILESTONES'].includes(x.paymentMode);const f=latest((await this.store.list<Funding>('fundingCommitments')).filter(v=>v.workspaceId===w&&v.milestoneId===i.milestoneId));const cert=latest((await this.store.list<Certificate>('completionCertificates')).filter(v=>v.workspaceId===w&&v.milestoneId===i.milestoneId));const pe=latest((await this.store.list<Eligibility>('paymentEligibilities')).filter(v=>v.workspaceId===w&&v.milestoneId===i.milestoneId));const inv=latest((await this.store.list<Invoice>('invoices')).filter(v=>v.workspaceId===w&&v.milestoneId===i.milestoneId&&v.status!=='REJECTED'));const held=(await this.store.list<Hold>('disputeHolds')).some(v=>v.workspaceId===w&&v.active&&v.milestoneId===i.milestoneId);const b:string[]=[];if(required&&f?.status!=='CONFIRMED')b.push('FUNDING_NOT_CONFIRMED');if(required&&f&&(f.currency!==x.currency||f.committedAmountMinor<x.amountMinor))b.push('FUNDING_INSTRUCTION_MISMATCH');if(cert?.status!=='CERTIFIED')b.push('COMPLETION_NOT_CERTIFIED');if(!pe?.eligible)b.push('PAYMENT_NOT_ELIGIBLE',...(pe?.blockers??[]).map(v=>`ELIGIBILITY:${v}`));if(inv?.status!=='APPROVED')b.push('INVOICE_NOT_APPROVED');if(inv&&(inv.currency!==x.currency||inv.amountMinor!==x.amountMinor))b.push('INVOICE_INSTRUCTION_MISMATCH');if(held)b.push('DISPUTE_HOLD_ACTIVE');const blockers=[...new Set(b)];const failed=[required&&blockers.some(v=>v.startsWith('FUNDING_')),blockers.includes('COMPLETION_NOT_CERTIFIED'),blockers.some(v=>v==='PAYMENT_NOT_ELIGIBLE'||v.startsWith('ELIGIBILITY:')),blockers.some(v=>v.startsWith('INVOICE_')),blockers.includes('DISPUTE_HOLD_ACTIVE')].filter(Boolean).length;const r:PaymentReadiness={id:randomUUID(),workspaceId:w,escrowInstructionId:x.id,milestoneId:i.milestoneId,score:Math.max(0,Math.round(((5-failed)/5)*100)),eligible:!blockers.length,blockers,evaluatedAt:now()};await this.store.append('paymentReadinessAssessments',r);await emit(this.store,c,'PaymentReadinessAssessed','PaymentReadiness',r.id,{milestoneId:r.milestoneId,score:r.score,eligible:r.eligible,blockers:r.blockers});return r}}
