import { createHash, randomUUID } from 'node:crypto';
import type { RequestContext, TrustPersistence } from '@assurapay/shared';
import { maskValue, requireActiveWorkspace } from '@assurapay/shared';
export type Party = { id: string; workspaceId: string; partyType: string; legalName: string; displayName: string; countryCode: string; status: 'ACTIVE' | 'SUSPENDED' | 'ARCHIVED'; verificationStatus: string; riskTier?: string; createdAt: string; updatedAt: string; version: number };
export type VerificationRequest = { id: string; workspaceId: string; partyId: string; verificationType: string; providerCode: string; providerRequestReference: string; status: 'PENDING' | 'COMPLETED' | 'FAILED'; requestedBy: string; requestedAt: string; expiresAt?: string; createdAt: string };
export type VerificationResult = { id: string; workspaceId: string; verificationRequestId: string; partyId: string; verificationType: string; result: 'VERIFIED' | 'FAILED' | 'REVIEW_REQUIRED'; riskFlags: string[]; matchedAttributes: string[]; sourceReferences: string[]; providerResponseReference: string; verifiedAt: string; expiresAt?: string; reviewStatus: 'PENDING' | 'APPROVED' | 'REJECTED' | 'NOT_REQUIRED'; reviewedBy?: string; reviewedAt?: string; supersedesResultId?: string; createdAt: string };
export type BeneficiaryAccount = { id: string; workspaceId: string; partyId: string; providerId?: string; accountReferenceToken: string; maskedAccountIdentifier: string; institutionName: string; currency: string; countryCode: string; verificationStatus: string; verifiedName?: string; verifiedAt?: string; status: 'ACTIVE' | 'DISABLED'; createdAt: string; updatedAt: string; version: number };
export interface VerificationProvider { readonly code: string; verify(input: { type: string; party: Party; attributes: Record<string, string> }): Promise<{ result: VerificationResult['result']; riskFlags: string[]; matchedAttributes: string[]; responseReference: string; expiresAt?: string }> }
export class DeterministicVerificationProvider implements VerificationProvider { readonly code = 'DETERMINISTIC_TEST'; async verify(input: { type: string; party: Party; attributes: Record<string, string> }) { const failed = Object.values(input.attributes).some((value) => value.toLowerCase().includes('fail')); return { result: failed ? 'FAILED' as const : 'VERIFIED' as const, riskFlags: failed ? ['TEST_FAILURE'] : [], matchedAttributes: Object.keys(input.attributes), responseReference: `sandbox:${createHash('sha256').update(`${input.party.id}:${input.type}`).digest('hex')}`, expiresAt: new Date(Date.now() + 365 * 86400000).toISOString() }; } }
const tokenize = (value: string) => createHash('sha256').update(`assurapay-token:${value}`).digest('hex');
export class PartyService {
  constructor(private readonly store: TrustPersistence, private readonly providers: VerificationProvider[]) {}
  async createParty(context: RequestContext, input: { partyType: string; legalName: string; displayName: string; countryCode: string; riskTier?: string }) { requireActiveWorkspace(context); const now = new Date().toISOString(); const party: Party = { id: randomUUID(), workspaceId: context.activeWorkspaceId, ...input, status: 'ACTIVE', verificationStatus: 'NOT_STARTED', createdAt: now, updatedAt: now, version: 1 }; await this.store.append('parties', party); await this.store.audit({ tenantId: context.tenantId, workspaceId: context.activeWorkspaceId, actorId: context.actorUserId, eventType: 'PartyCreated', aggregateType: 'Party', aggregateId: party.id, correlationId: context.correlationId, metadata: { partyType: party.partyType } }); return party; }
  async requestVerification(context: RequestContext, input: { partyId: string; verificationType: string; providerCode: string; attributes: Record<string, string> }) { requireActiveWorkspace(context); const party = await this.requireParty(input.partyId, context.activeWorkspaceId); const provider = this.providers.find((entry) => entry.code === input.providerCode); if (!provider) throw new Error('VERIFICATION_PROVIDER_NOT_FOUND'); const now = new Date().toISOString(); const request: VerificationRequest = { id: randomUUID(), workspaceId: context.activeWorkspaceId, partyId: party.id, verificationType: input.verificationType, providerCode: provider.code, providerRequestReference: randomUUID(), status: 'PENDING', requestedBy: context.actorUserId, requestedAt: now, createdAt: now }; await this.store.append('verificationRequests', request); const providerResult = await provider.verify({ type: input.verificationType, party, attributes: input.attributes }); const result: VerificationResult = { id: randomUUID(), workspaceId: context.activeWorkspaceId, verificationRequestId: request.id, partyId: party.id, verificationType: input.verificationType, result: providerResult.result, riskFlags: [...providerResult.riskFlags], matchedAttributes: [...providerResult.matchedAttributes], sourceReferences: [], providerResponseReference: providerResult.responseReference, verifiedAt: new Date().toISOString(), expiresAt: providerResult.expiresAt, reviewStatus: providerResult.result === 'REVIEW_REQUIRED' ? 'PENDING' : 'NOT_REQUIRED', createdAt: new Date().toISOString() }; await this.store.append('verificationResults', result); await this.store.replace('verificationRequests', { ...request, status: result.result === 'FAILED' ? 'FAILED' : 'COMPLETED' }); const current = await this.currentVerificationStatus(party.id, context.activeWorkspaceId); await this.store.replace('parties', { ...party, verificationStatus: current, updatedAt: new Date().toISOString(), version: party.version + 1 }); await this.store.audit({ tenantId: context.tenantId, workspaceId: context.activeWorkspaceId, actorId: context.actorUserId, eventType: result.result === 'FAILED' ? 'VerificationFailed' : 'VerificationCompleted', aggregateType: 'VerificationResult', aggregateId: result.id, correlationId: context.correlationId, metadata: { type: input.verificationType, provider: provider.code, result: result.result } }); return result; }
  async reviewResult(context: RequestContext, id: string, decision: 'APPROVED' | 'REJECTED') { requireActiveWorkspace(context); const original = (await this.store.list<VerificationResult>('verificationResults')).find((entry) => entry.id === id && entry.workspaceId === context.activeWorkspaceId); if (!original) throw new Error('VERIFICATION_RESULT_NOT_FOUND'); const reviewed: VerificationResult = { ...structuredClone(original), id: randomUUID(), reviewStatus: decision, reviewedBy: context.actorUserId, reviewedAt: new Date().toISOString(), supersedesResultId: original.id, createdAt: new Date().toISOString() }; await this.store.append('verificationResults', reviewed); return reviewed; }
  async currentVerificationStatus(partyId: string, workspaceId: string) { const current = (await this.store.list<VerificationResult>('verificationResults')).filter((entry) => entry.partyId === partyId && entry.workspaceId === workspaceId && (!entry.expiresAt || Date.parse(entry.expiresAt) > Date.now())).sort((a, b) => Date.parse(b.createdAt) - Date.parse(a.createdAt)); if (!current.length) return 'NOT_STARTED'; if (current.some((entry) => entry.result === 'FAILED')) return 'FAILED'; return current.some((entry) => entry.result === 'VERIFIED') ? 'VERIFIED' : 'REVIEW_REQUIRED'; }
  async addBeneficiary(context: RequestContext, input: { partyId: string; rawAccountReference: string; institutionName: string; currency: string; countryCode: string; providerId?: string }) { requireActiveWorkspace(context); await this.requireParty(input.partyId, context.activeWorkspaceId); const now = new Date().toISOString(); const account: BeneficiaryAccount = { id: randomUUID(), workspaceId: context.activeWorkspaceId, partyId: input.partyId, providerId: input.providerId, accountReferenceToken: tokenize(input.rawAccountReference), maskedAccountIdentifier: maskValue(input.rawAccountReference, 'LAST_FOUR'), institutionName: input.institutionName, currency: input.currency, countryCode: input.countryCode, verificationStatus: 'NOT_STARTED', status: 'ACTIVE', createdAt: now, updatedAt: now, version: 1 }; await this.store.append('beneficiaryAccounts', account); await this.store.audit({ tenantId: context.tenantId, workspaceId: context.activeWorkspaceId, actorId: context.actorUserId, eventType: 'BeneficiaryAccountAdded', aggregateType: 'BeneficiaryAccount', aggregateId: account.id, correlationId: context.correlationId, metadata: { institutionName: input.institutionName } }); return account; }
  async serializeParty(context: RequestContext, id: string) { requireActiveWorkspace(context); const party = await this.requireParty(id, context.activeWorkspaceId); return { ...party, beneficiaries: (await this.store.list<BeneficiaryAccount>('beneficiaryAccounts')).filter((entry) => entry.partyId === id && entry.workspaceId === context.activeWorkspaceId).map(({ accountReferenceToken: _token, ...safe }) => safe) }; }
  private async requireParty(id: string, workspaceId: string) { const party = (await this.store.list<Party>('parties')).find((entry) => entry.id === id && entry.workspaceId === workspaceId); if (!party) throw new Error('PARTY_NOT_FOUND'); return party; }
}
