import { createHash, randomUUID } from 'node:crypto';
import type { RequestContext, TrustPersistence } from '@assurapay/shared';
import { requireActiveWorkspace } from '@assurapay/shared';
export type Workspace = { id: string; workspaceType: 'PERSONAL' | 'ORGANIZATION'; name: string; slug: string; ownerUserId: string; tenantId: string; status: 'ACTIVE' | 'SUSPENDED' | 'ARCHIVED'; defaultCurrency: string; timezone: string; countryCode: string; createdAt: string; updatedAt: string; version: number };
export type Membership = { id: string; workspaceId: string; userId: string; membershipType: 'OWNER' | 'MEMBER' | 'EXTERNAL'; status: 'INVITED' | 'ACTIVE' | 'SUSPENDED' | 'ENDED' | 'REVOKED'; invitedBy: string; invitedAt: string; acceptedAt?: string; suspendedAt?: string; endedAt?: string; createdAt: string; updatedAt: string; version: number };
export type Organization = { id: string; workspaceId: string; legalName: string; tradingName?: string; organizationType: string; registrationNumber?: string; taxIdentifierToken?: string; industry: string; businessSize: string; countryCode: string; registeredAddress: string; verificationStatus: string; status: 'ACTIVE' | 'SUSPENDED' | 'ARCHIVED'; createdAt: string; updatedAt: string; version: number };
export type OrganizationUnit = { id: string; workspaceId: string; organizationId: string; parentUnitId?: string; unitType: string; name: string; code: string; status: 'ACTIVE' | 'INACTIVE'; effectiveFrom: string; createdAt: string; updatedAt: string; version: number };
export type Invitation = { id: string; workspaceId: string; email: string; invitedRoleReference: string; invitationTokenHash: string; status: 'PENDING' | 'ACCEPTED' | 'EXPIRED' | 'REVOKED'; invitedBy: string; expiresAt: string; acceptedBy?: string; acceptedAt?: string; createdAt: string };
const tokenHash = (value: string) => createHash('sha256').update(value).digest('hex');
export class OrganizationService {
  constructor(private readonly store: TrustPersistence) {}
  async createWorkspace(input: { workspaceType: Workspace['workspaceType']; name: string; slug: string; ownerUserId: string; defaultCurrency: string; timezone: string; countryCode: string; correlationId: string }) { if ((await this.store.list<Workspace>('trustWorkspaces')).some((entry) => entry.slug === input.slug)) throw new Error('WORKSPACE_SLUG_EXISTS'); const now = new Date().toISOString(); const workspace: Workspace = { id: randomUUID(), ...input, tenantId: randomUUID(), status: 'ACTIVE', createdAt: now, updatedAt: now, version: 1 }; await this.store.append('trustWorkspaces', workspace); const membership: Membership = { id: randomUUID(), workspaceId: workspace.id, userId: input.ownerUserId, membershipType: 'OWNER', status: 'ACTIVE', invitedBy: input.ownerUserId, invitedAt: now, acceptedAt: now, createdAt: now, updatedAt: now, version: 1 }; await this.store.append('memberships', membership); await this.store.audit({ tenantId: workspace.tenantId, workspaceId: workspace.id, actorId: input.ownerUserId, eventType: 'WorkspaceCreated', aggregateType: 'Workspace', aggregateId: workspace.id, correlationId: input.correlationId, metadata: { workspaceType: input.workspaceType } }); await this.store.emit({ tenantId: workspace.tenantId, workspaceId: workspace.id, aggregateType: 'Workspace', aggregateId: workspace.id, eventType: input.workspaceType === 'PERSONAL' ? 'PersonalWorkspaceCreated' : 'OrganizationWorkspaceCreated', eventVersion: 1, payload: { ownerUserId: input.ownerUserId }, correlationId: input.correlationId }); return workspace; }
  async createOrganization(context: RequestContext, input: Omit<Organization, 'id' | 'workspaceId' | 'taxIdentifierToken' | 'verificationStatus' | 'status' | 'createdAt' | 'updatedAt' | 'version'> & { taxIdentifier?: string }) { requireActiveWorkspace(context); const workspace = await this.requireWorkspace(context.activeWorkspaceId); if (workspace.workspaceType !== 'ORGANIZATION') throw new Error('ORGANIZATION_WORKSPACE_REQUIRED'); await this.requireMembership(context.actorUserId, workspace.id); const now = new Date().toISOString(); const organization: Organization = { id: randomUUID(), ...input, workspaceId: workspace.id, taxIdentifierToken: input.taxIdentifier ? tokenHash(input.taxIdentifier) : undefined, verificationStatus: 'NOT_STARTED', status: 'ACTIVE', createdAt: now, updatedAt: now, version: 1 }; await this.store.append('trustOrganizations', organization); await this.store.audit({ tenantId: workspace.tenantId, workspaceId: workspace.id, actorId: context.actorUserId, eventType: 'OrganizationCreated', aggregateType: 'Organization', aggregateId: organization.id, correlationId: context.correlationId, metadata: {} }); return organization; }
  async invite(context: RequestContext, input: { email: string; roleReference: string; rawToken: string; expiresAt: string }) { requireActiveWorkspace(context); await this.requireMembership(context.actorUserId, context.activeWorkspaceId); const invitation: Invitation = { id: randomUUID(), workspaceId: context.activeWorkspaceId, email: input.email.toLowerCase(), invitedRoleReference: input.roleReference, invitationTokenHash: tokenHash(input.rawToken), status: 'PENDING', invitedBy: context.actorUserId, expiresAt: input.expiresAt, createdAt: new Date().toISOString() }; await this.store.append('invitations', invitation); return invitation; }
  async acceptInvitation(rawToken: string, userId: string) { const invitation = (await this.store.list<Invitation>('invitations')).find((entry) => entry.invitationTokenHash === tokenHash(rawToken)); if (!invitation || invitation.status !== 'PENDING' || Date.parse(invitation.expiresAt) <= Date.now()) throw new Error('INVITATION_INVALID'); const now = new Date().toISOString(); await this.store.replace('invitations', { ...invitation, status: 'ACCEPTED', acceptedBy: userId, acceptedAt: now }); const membership: Membership = { id: randomUUID(), workspaceId: invitation.workspaceId, userId, membershipType: 'MEMBER', status: 'ACTIVE', invitedBy: invitation.invitedBy, invitedAt: invitation.createdAt, acceptedAt: now, createdAt: now, updatedAt: now, version: 1 }; await this.store.append('memberships', membership); return membership; }
  async updateMembership(id: string, context: RequestContext, status: Membership['status']) { requireActiveWorkspace(context); const membership = (await this.store.list<Membership>('memberships')).find((entry) => entry.id === id && entry.workspaceId === context.activeWorkspaceId); if (!membership) throw new Error('MEMBERSHIP_NOT_FOUND'); const now = new Date().toISOString(); const updated = { ...membership, status, suspendedAt: status === 'SUSPENDED' ? now : membership.suspendedAt, endedAt: status === 'ENDED' ? now : membership.endedAt, updatedAt: now, version: membership.version + 1 }; await this.store.replace('memberships', updated); return updated; }
  async createUnit(context: RequestContext, input: { organizationId: string; parentUnitId?: string; unitType: string; name: string; code: string }) { requireActiveWorkspace(context); await this.requireMembership(context.actorUserId, context.activeWorkspaceId); const organization = (await this.store.list<Organization>('trustOrganizations')).find((entry) => entry.id === input.organizationId && entry.workspaceId === context.activeWorkspaceId); if (!organization) throw new Error('ORGANIZATION_NOT_FOUND'); if (input.parentUnitId) { const parent = (await this.store.list<OrganizationUnit>('organizationUnits')).find((entry) => entry.id === input.parentUnitId && entry.workspaceId === context.activeWorkspaceId && entry.organizationId === input.organizationId); if (!parent) throw new Error('PARENT_UNIT_NOT_FOUND'); } const now = new Date().toISOString(); const unit: OrganizationUnit = { id: randomUUID(), workspaceId: context.activeWorkspaceId, ...input, status: 'ACTIVE', effectiveFrom: now, createdAt: now, updatedAt: now, version: 1 }; await this.store.append('organizationUnits', unit); return unit; }
  async moveUnit(id: string, parentUnitId: string | undefined, context: RequestContext) { requireActiveWorkspace(context); const units = await this.store.list<OrganizationUnit>('organizationUnits'); const unit = units.find((entry) => entry.id === id && entry.workspaceId === context.activeWorkspaceId); if (!unit) throw new Error('UNIT_NOT_FOUND'); let cursor = parentUnitId; while (cursor) { if (cursor === id) throw new Error('ORGANIZATION_HIERARCHY_CYCLE'); cursor = units.find((entry) => entry.id === cursor)?.parentUnitId; } const updated = { ...unit, parentUnitId, updatedAt: new Date().toISOString(), version: unit.version + 1 }; await this.store.replace('organizationUnits', updated); return updated; }
  async listAuthorizedWorkspaces(userId: string) { const ids = new Set((await this.store.list<Membership>('memberships')).filter((entry) => entry.userId === userId && entry.status === 'ACTIVE').map((entry) => entry.workspaceId)); return (await this.store.list<Workspace>('trustWorkspaces')).filter((entry) => ids.has(entry.id) && entry.status === 'ACTIVE'); }
  async activateContext(userId: string, workspaceId: string, sessionId: string, assurance: RequestContext['identityAssuranceLevel']): Promise<RequestContext> { const membership = await this.requireMembership(userId, workspaceId); const workspace = await this.requireWorkspace(workspaceId); return { actorUserId: userId, sessionId, identityAssuranceLevel: assurance, activeWorkspaceId: workspaceId, tenantId: workspace.tenantId, memberships: (await this.listAuthorizedWorkspaces(userId)).map((entry) => entry.id), correlationId: randomUUID() }; }
  private async requireWorkspace(id: string) { const workspace = (await this.store.list<Workspace>('trustWorkspaces')).find((entry) => entry.id === id); if (!workspace) throw new Error('WORKSPACE_NOT_FOUND'); return workspace; }
  private async requireMembership(userId: string, workspaceId: string) { const membership = (await this.store.list<Membership>('memberships')).find((entry) => entry.userId === userId && entry.workspaceId === workspaceId && entry.status === 'ACTIVE'); if (!membership) throw new Error('WORKSPACE_ACCESS_DENIED'); return membership; }
}
