import { cell, markdownTable } from '../util/serialize.ts';
import { selectNext } from '../backlog.ts';
import { REOS_VERSION } from '../types.ts';
import type { DependencyResolution, ExecutionManifest } from '../types.ts';

/**
 * Stage 4 — deterministic selection of the next capability to implement.
 *
 * Every exclusion is recorded with its reason, so the choice is auditable
 * rather than a black box. The four hard rules are:
 *   1. never duplicate completed work,
 *   2. never violate dependencies,
 *   3. never bypass certification,
 *   4. never select blocked work.
 */
export function resolveDependencies(
  manifest: ExecutionManifest,
): DependencyResolution {
  const backlog = manifest.executionBacklog;
  const executable = backlog.filter((entry) => entry.executable);
  const blocked = backlog.filter((entry) => !entry.executable);
  const selected = selectNext(backlog);

  const selectionReason = selected
    ? [
        'Highest-priority executable capability',
        `(priority ${selected.priority}, lifecycle ${selected.lifecycle})`,
        selected.requiresLiveInfrastructure
          ? '— selected despite needing live infrastructure, nothing else is executable'
          : '',
        selected.blocks.length > 0
          ? `— unblocks ${selected.blocks.length} downstream capability/-ies`
          : '',
      ]
        .filter((part) => part.length > 0)
        .join(' ')
    : null;

  const rejected = [
    ...blocked.map((entry) => ({
      id: entry.id,
      reason: `Blocked by unmet dependencies: ${entry.blockedBy.join(', ')}.`,
    })),
    ...executable
      .filter((entry) => selected === null || entry.id !== selected.id)
      .map((entry) => ({
        id: entry.id,
        reason: entry.requiresLiveInfrastructure
          ? 'Executable but deprioritised: requires live infrastructure.'
          : `Executable but lower priority than the selected capability (${entry.priority}).`,
      })),
  ].sort((left, right) => left.id.localeCompare(right.id));

  return {
    reosVersion: REOS_VERSION,
    stage: 'dependencies',
    head: manifest.identity.head,
    selected,
    selectionReason,
    rejected,
    executable,
    blocked,
    completed: manifest.implementedCapabilities,
    awaitingInfrastructure: backlog
      .filter((entry) => entry.requiresLiveInfrastructure)
      .map((entry) => entry.id)
      .sort(),
  };
}

export function renderDependencyResolution(
  resolution: DependencyResolution,
): string {
  const selected = resolution.selected;

  return [
    '# Dependency Resolution Report',
    '',
    '> Generated by `pnpm repo:dependencies`. Do not edit by hand.',
    '',
    '## Selected capability',
    '',
    selected
      ? markdownTable(
          ['Field', 'Value'],
          [
            ['Capability', cell(selected.id)],
            ['Title', cell(selected.title)],
            ['Current status', selected.status],
            ['Lifecycle', selected.lifecycle],
            ['Priority', String(selected.priority)],
            ['Reason', cell(resolution.selectionReason)],
            ['Depends on', selected.dependsOn.length > 0 ? cell(selected.dependsOn.join(', ')) : '—'],
            ['Unmet dependencies', selected.blockedBy.length > 0 ? cell(selected.blockedBy.join(', ')) : 'none'],
            ['Blocks (transitive)', selected.blocks.length > 0 ? cell(selected.blocks.join(', ')) : '—'],
            [
              'Declared scope',
              `${selected.scope.files} file(s), ${selected.scope.tests} test suite(s)${
                selected.scope.estimated ? ' (registry estimate)' : ''
              }`,
            ],
            [
              'Requires live infrastructure',
              selected.requiresLiveInfrastructure ? 'yes' : 'no',
            ],
          ],
        )
      : 'No executable capability. Every backlog item is blocked, deferred or complete.',
    '',
    '## Executable queue',
    '',
    resolution.executable.length > 0
      ? markdownTable(
          ['Capability', 'Title', 'Lifecycle', 'Priority', 'Blocks', 'Live infra'],
          resolution.executable.map((entry) => [
            cell(entry.id),
            cell(entry.title),
            entry.lifecycle,
            String(entry.priority),
            entry.blocks.length > 0 ? String(entry.blocks.length) : '—',
            entry.requiresLiveInfrastructure ? 'yes' : 'no',
          ]),
        )
      : 'Empty.',
    '',
    '## Blocked',
    '',
    resolution.blocked.length > 0
      ? markdownTable(
          ['Capability', 'Status', 'Blocked by'],
          resolution.blocked
            .slice(0, 30)
            .map((entry) => [
              cell(entry.id),
              entry.status,
              cell(entry.blockedBy.join(', ')),
            ]),
        )
      : 'Nothing blocked.',
    '',
    '## Awaiting live infrastructure',
    '',
    resolution.awaitingInfrastructure.length > 0
      ? resolution.awaitingInfrastructure.map((id) => `- ${id}`).join('\n')
      : 'None.',
    '',
    `## Completed (${resolution.completed.length})`,
    '',
    resolution.completed.length > 0
      ? resolution.completed.map((id) => `- ${id}`).join('\n')
      : 'None.',
    '',
  ].join('\n');
}
