import { changedFiles } from '../util/git.ts';
import { cell, markdownTable } from '../util/serialize.ts';
import { validateArchitecture } from '../validators/architecture.ts';
import { validateDependencies } from '../validators/dependency.ts';
import { validateSecurity } from '../validators/security.ts';
import { validateExecutionContract } from '../validators/contract.ts';
import { resolveBase } from '../validators/contract.ts';
import { REOS_VERSION } from '../types.ts';
import type {
  CertificationReport,
  DependencyResolution,
  DiscoverySnapshot,
  ExecutionManifest,
  ExecutionReport,
} from '../types.ts';

/** Stage 7 — the closing record of one execution session. */
export function buildExecutionReport(
  repoRoot: string,
  discovery: DiscoverySnapshot,
  manifest: ExecutionManifest,
  resolution: DependencyResolution,
  certification: CertificationReport | null,
  options: { capability?: string | null } = {},
): ExecutionReport {
  const git = discovery.repository.git;
  const failedSteps = (certification?.steps ?? [])
    .filter((step) => !step.passed && !step.skipped)
    .map((step) => step.id);

  return {
    reosVersion: REOS_VERSION,
    stage: 'report',
    generatedAt: new Date().toISOString(),
    repositoryState: {
      branch: git.branch,
      head: git.head,
      clean: git.clean,
      dirtyFiles: git.dirtyFiles,
    },
    capability: options.capability ?? null,
    filesModified: changedFiles(repoRoot, resolveBase(repoRoot)),
    validation: [
      validateArchitecture(repoRoot, discovery),
      validateDependencies(repoRoot, discovery),
      validateSecurity(repoRoot),
      validateExecutionContract(repoRoot, discovery),
    ],
    certification: {
      available: certification !== null,
      passed: certification?.passed ?? false,
      failedSteps,
    },
    remainingBacklog: manifest.executionBacklog,
    recommendedNextCapability: resolution.selected,
    commit: git.head,
  };
}

export function renderExecutionReport(report: ExecutionReport): string {
  const validationRows = report.validation.map((outcome) => [
    cell(outcome.validator),
    outcome.passed ? 'pass' : '**fail**',
    String(outcome.checked),
    String(outcome.findings.filter((finding) => finding.severity === 'error').length),
    String(outcome.findings.filter((finding) => finding.severity === 'warning').length),
  ]);

  const allFindings = report.validation.flatMap((outcome) => outcome.findings);

  return [
    '# Execution Report',
    '',
    '> Generated by `pnpm repo:report`. Do not edit by hand.',
    '',
    '## Repository state',
    '',
    markdownTable(
      ['Field', 'Value'],
      [
        ['Branch', cell(report.repositoryState.branch)],
        ['HEAD', cell(report.repositoryState.head)],
        ['Worktree clean', report.repositoryState.clean ? 'yes' : 'no'],
        ['Uncommitted files', String(report.repositoryState.dirtyFiles.length)],
        ['Generated at', cell(report.generatedAt)],
      ],
    ),
    '',
    '## Capability implemented',
    '',
    report.capability ? `\`${report.capability}\`` : 'None declared for this session.',
    '',
    `## Files modified (${report.filesModified.length})`,
    '',
    report.filesModified.length > 0
      ? report.filesModified.map((file) => `- \`${file}\``).join('\n')
      : 'No changes relative to the comparison base.',
    '',
    '## Validation',
    '',
    markdownTable(
      ['Validator', 'Result', 'Checked', 'Errors', 'Warnings'],
      validationRows,
    ),
    '',
    ...(allFindings.length > 0
      ? [
          '### Findings',
          '',
          ...allFindings.map(
            (finding) =>
              `- **${finding.severity}** \`${finding.rule}\`${
                finding.location ? ` (${finding.location})` : ''
              } — ${finding.message}`,
          ),
          '',
        ]
      : []),
    '## Certification',
    '',
    report.certification.available
      ? report.certification.passed
        ? '**PASSED** — every certification gate is green.'
        : `**FAILED** — failing steps: ${report.certification.failedSteps.join(', ')}.`
      : 'Not run in this session. Execute `pnpm repo:certify`.',
    '',
    `## Remaining backlog (${report.remainingBacklog.length})`,
    '',
    report.remainingBacklog.length > 0
      ? markdownTable(
          ['Capability', 'Status', 'Executable', 'Blocked by'],
          report.remainingBacklog
            .slice(0, 20)
            .map((entry) => [
              cell(entry.id),
              entry.status,
              entry.executable ? 'yes' : 'no',
              cell(entry.blockedBy.join(', ')),
            ]),
        )
      : 'Backlog empty.',
    '',
    '## Recommended next capability',
    '',
    report.recommendedNextCapability
      ? `\`${report.recommendedNextCapability.id}\` — ${report.recommendedNextCapability.title}`
      : 'None available.',
    '',
    '## Commit',
    '',
    `\`${report.commit}\``,
    '',
  ].join('\n');
}
